### ISSUE TITLE
add searching program in java 

### ISSUE THREAD

**Issue by Suryansh1720001** [dasundev/hacktoberfest-2022#152]

**Comment by Suryansh1720001** [comment]
I'd like to contribute to this issue with this issue.

**Comment by Suryansh1720001** [comment]
I'd like to contribute to this issue.

**Comment by NipunaNiranjan** [comment]
Could plz assign me !!!

**Comment by amaan0810** [comment]
I would to contribute under hacktoberfest

**Comment by amaan0810** [comment]
I would like to contribute under hacktoberfest

**Comment by SE-LAPS** [comment]
sir, please assign me this issue..

**Comment by Danish-Belal** [comment]
@dasundev  Kindly assign this issue to me i m really looking forward to work on it. Thanks

**Comment by SE-LAPS** [comment]
add
